### PR TITLE
Cleanup Make, add editor configs and change tabs to spaces

### PR DESCRIPTION
**Pull request by alerque**
@curiousdannii Can you review this before it actually gets merged? If we're going to change the whitespace style I'd rather do it by fixing these commits rather than merging reverts for them again later.

In chat [you mentioned](http://chat.stackexchange.com/transcript/34086?m=26799140#26799140) using 4 space tabs, which was fine with me. Its unusual in the js world these days, but I use an indent/unindent function that just uses whatever coding style is configured for the project anyway so its no sweat off my back. But then you setup the linter to use 2 space tabs. This isn't so fine with me. I can handle two space indents _or_ tabs, but not both. I work almost exclusively on the terminal and console programs make a lot of assumptions about tabs. Even things like `diff` and `less` don't play nice with mix and match like that. Tabs are assumed to be 4 spaces in too many places.

I understand two-space indent is pretty much the  norm in Javascript circles these days, so we can go with that if you like, but it has to be two spaces, not half-tabs ;-) At the very least we should use this for json data as most tools assume it.

If you want to go back to 4 space (using spaces or tabs) we can do that, just let me know and I'll rebase these commits.

### CODE REVIEW

**Comment by curiousdannii** [comment]
@alerque Oh, no I didn't explain myself clearly. I prefer hard tabs. When I said "4 spaces" I meant only how I like to have those tabs displayed (which I think is pretty common now but not at all universal). The "2" in .eslintrc.yml means that the rule is set to be an error, making eslint give a failing exit code. "1" rules are warnings and don't fail, while "0" disables rules. I use hard tabs in my hand-edited json files too, so only the package.json file would have 2-space indents because that's how npm edits it. But I'd be okay with 2 space indents for json files if you'd prefer that.

Sorry for all the confusion! I hope this didn't take you too much time.

The other changes all look good. I didn't know about EditorConfig - it looks quite useful. I'll install its plugins in my editors.

**Comment by alerque** [comment]
@curiousdannii Sorry I didn't understand what was going on there, then I created a race condition in my head. I read the eslint config first, then wrote the editor config based on parsing that in my head, _then and only then_ did I look at the actual JS files and sure enough the tabs were showing up as two spaces. Like I configured them to in the editor-config. For some reason I didn't put two and two together and thought eslint had done that. Oops. Reverted.

Tabs is fine by me for code, but for json data I suggest we keep to the community standards so that we can run it through whatever third party tools and parsers (such as `jq` or linters) we like with impunity because we'll get the same thing out as we put in. Many tools allow extra flags or settings to get non standard output (as I imagine we could configure so npm would allow in  it package.json) but I don't think its worth the trouble and suggest we just normalize them at two spaces and leave rocking the node community's boat for another voyage.

If you care about hitting the tab key, the editor config should take care of that so that tab at the start of a line inserts two spaces. If you are adamant about _seeing_ 4 space tabs in json then I'll bust out a git smudge/clean filter you you ;-)

How do the rebased commits look now?

**Comment by curiousdannii** [comment]
LGTM. I liked blank lines having the same indentation as their surrounding code, but that's a small price to pay for consistent tools.

I snuck in an extra commit, so lets merge it as soon as Travis is finished.

**Comment by alerque** [comment]
You've obviously never had to work with LaTeX! Or Python for that matter. Those of us who have are scarred for life and will never be comfortable in the same room with trailing whitespace.

**Pull request merged**
